export const SECTOR_LABELS: Record<string, string> = {
  IT_SERVICES: 'IT Services & Consulting',
  ACCOUNTING: 'Accounting & Audit',
  ECOMMERCE: 'E-Commerce & Retail Tech',
  INTERNET_PLATFORMS: 'Internet & Software Platforms',
  CONSULTING: 'Management Consulting',
  SEMICONDUCTOR_MFG: 'Semiconductor Manufacturing',
  PHARMA: 'Pharmaceuticals',
  BANKING: 'Banking & Finance',
  INSURANCE: 'Insurance',
  UNIVERSITIES: 'Universities & Research',
  HOSPITALS: 'Hospitals & Health Systems',
  INVESTMENT_SECURITIES: 'Investment & Securities',
  ADMIN_SUPPORT: 'Administrative & Staffing',
  TELECOM: 'Telecommunications',
  AUTOMOTIVE_MFG: 'Automotive Manufacturing',
  AEROSPACE_MFG: 'Aerospace & Defense',
  HOLDING_COMPANIES: 'Diversified Holdings',
  SCIENTIFIC_RD: 'Scientific R&D',
  ENGINEERING_SERVICES: 'Engineering Services',
  LEGAL: 'Legal Services',
  AI_DIGITAL_PLATFORMS: 'AI & Digital Platforms',
  COMPUTER_ELECTRONICS_MFG: 'Computer & Electronics Mfg',
  CLOUD_DATA: 'Cloud & Data Services',
  DEPARTMENT_STORES: 'Retail & Department Stores',
}

export const STATE_NAMES: Record<string, string> = {
  AL: 'Alabama', AK: 'Alaska', AZ: 'Arizona', AR: 'Arkansas',
  CA: 'California', CO: 'Colorado', CT: 'Connecticut', DE: 'Delaware',
  DC: 'District of Columbia', FL: 'Florida', GA: 'Georgia', HI: 'Hawaii',
  ID: 'Idaho', IL: 'Illinois', IN: 'Indiana', IA: 'Iowa',
  KS: 'Kansas', KY: 'Kentucky', LA: 'Louisiana', ME: 'Maine',
  MD: 'Maryland', MA: 'Massachusetts', MI: 'Michigan', MN: 'Minnesota',
  MS: 'Mississippi', MO: 'Missouri', MT: 'Montana', NE: 'Nebraska',
  NV: 'Nevada', NH: 'New Hampshire', NJ: 'New Jersey', NM: 'New Mexico',
  NY: 'New York', NC: 'North Carolina', ND: 'North Dakota', OH: 'Ohio',
  OK: 'Oklahoma', OR: 'Oregon', PA: 'Pennsylvania', RI: 'Rhode Island',
  SC: 'South Carolina', SD: 'South Dakota', TN: 'Tennessee', TX: 'Texas',
  UT: 'Utah', VT: 'Vermont', VA: 'Virginia', WA: 'Washington',
  WV: 'West Virginia', WI: 'Wisconsin', WY: 'Wyoming',
}

export const SITE_NAME = 'StudyCareer'
export const SITE_DESCRIPTION = 'H1B & green card data for every US employer'
